# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEuropeanUpOutCallPrice <- function(nInt, strike, barrier, spot, vol, r, expiry, nReps = 1000L) {
    .Call(`_EUoutCalloptionPricer_getEuropeanUpOutCallPrice`, nInt, strike, barrier, spot, vol, r, expiry, nReps)
}

