# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEuropeanUpOutCallPrice <- function(nInt = 126L, strike = 100, barrier = 130, spot = 95, vol = 0.24, r = 0.07, expiry = 0.75, nReps = 1000L) {
    .Call(`_EUoutCalloptionPricer_getEuropeanUpOutCallPrice`, nInt, strike, barrier, spot, vol, r, expiry, nReps)
}

